// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryvqhyhgkhvkrnwxkbvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5dnFoeWhna2h2a3Jud3hrYnZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzcyNDAsImV4cCI6MjA2NDcxMzI0MH0.joBGTZoDOxuQo1AzLbbsEQ8E8sTeGJQhoRzTMzpfo5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);